# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bbdf77494c80489e98042c9f89cc535e"
name = "MEMEXCLU"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts, read_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]


